export const GAME_CONFIG = {
  arena: {
    halfSize: 24,
    backgroundColor: 0x101820,
    groundColor: 0x24343b,
    gridColor: 0x4b6870,
  },
  player: {
    maxHp: 100,
    armor: 0,
    armorFormulaConstant: 100,
    dodgeChance: 0,
    dodgeChanceCap: 0.75,
    hpRegenPerSecond: 0,
    pickupRange: 4.5,
    moveSpeed: 8,
    radius: 0.65,
    color: 0x66e3c4,
  },
  enemy: {
    maxHp: 30,
    moveSpeed: 2.2,
    radius: 0.55,
    color: 0xef476f,
    xpReward: 12,
    rewards: {
      Chaser: { xp: 12, money: 1 },
      Runner: { xp: 10, money: 1 },
      Shooter: { xp: 15, money: 2 },
      Charger: { xp: 18, money: 2 },
      ElementEnemy: { xp: 30, money: 3 },
    },
    contactDamage: 10,
    contactInterval: 0.9,
    archetypes: {
      runner: { hpMultiplier: 0.55, speedMultiplier: 1.75, color: 0xff9f43 },
      shooter: {
        hpMultiplier: 0.8,
        speedMultiplier: 0.9,
        preferredDistance: 8,
        distanceBand: 1.5,
        attackInterval: 1.8,
        color: 0xb56cff,
      },
      charger: {
        hpMultiplier: 1.35,
        speedMultiplier: 0.85,
        trackingDuration: 2.2,
        windupDuration: 0.7,
        chargeDuration: 0.55,
        chargeSpeed: 13,
        cooldown: 2.4,
        color: 0xff3d54,
      },
    },
    projectile: {
      speed: 8,
      damage: 8,
      radius: 0.22,
      lifetime: 5,
      color: 0xff6b35,
      multiShotAngle: 0.2,
    },
    elite: {
      fastSpeedMultiplier: 1.45,
      tankyHpMultiplier: 2.5,
      rapidFireIntervalMultiplier: 0.55,
      multiShotCount: 3,
      radialBurstInterval: 3.5,
      radialBurstCount: 8,
      sizeMultiplier: 1.25,
    },
    healthRing: {
      visibleDuration: 3,
      innerRadius: 0.72,
      outerRadius: 0.88,
      worldHeight: 0.2,
      segments: 48,
      renderOrder: 1000,
      backgroundColor: 0x11131a,
      foregroundColor: 0xffdf4f,
    },
    progression: {
      runnerUnlockRound: 3,
      shooterUnlockRound: 5,
      chargerUnlockRound: 7,
      eliteUnlockRound: 9,
      runnerWeight: 0.2,
      shooterWeight: 0.17,
      chargerWeight: 0.13,
      eliteChance: 0.1,
    },
  },
  economy: {
    eliteMoneyMin: 3,
    eliteMoneyMax: 5,
    pickupRadius: 0.35,
    pickupContactDistance: 0.75,
    pickupMagnetSpeed: 12,
    pickupLifetime: 300,
    pickupColor: 0x4cff72,
    estimatedEnemiesPerRound: 52,
    targetClearRate: 0.75,
    targetRoundIncome: 35,
    roundEndMoneyAutoCollectRatio: 0.5,
  },
  rounds: {
    firstRoundDuration: 30,
    normalRoundDuration: 60,
    roundClearPauseSeconds: 1,
    plannedCount: 20,
    difficulty: {
      enemyHpPerRound: 0.08,
      enemySpeedPerRound: 0.04,
      spawnRatePerRound: 0.08,
    },
  },
  elements: {
    evolveKey: 'KeyE',
    elementSpawnSchedule: { 2: 1, 5: 2 } as Readonly<Record<number, number>>,
    elementEnemySpawnDelaySeconds: 20,
    evolutionTutorialDurationSeconds: 4,
    enemySizeMultiplier: 1.35,
    enemyHpMultiplier: 8.3,
    /** A small Round 5-only adjustment; other scheduled element rounds retain the base value. */
    enemyHpMultiplierByRound: { 5: 0.88 } as Readonly<Record<number, number>>,
    enemySpeedMultiplier: 1.2,
    spawnDistance: 13,
    corePickupRadius: 1.25,
    coreLifetime: 180,
    tier2ElementCoreMoneyValue: 10,
  },
  skills: {
    poisonStackCap: 5,
    tier1: {
      damage: 22,
      cooldown: 0.68,
      range: 11,
      fireBurnDamage: 4,
      fireBurnDuration: 2.4,
      waterSplashDamage: 11,
      waterSplashRadius: 1.8,
      earthSlowMultiplier: 0.55,
      earthSlowDuration: 1.5,
      windProjectileSpeed: 25,
      windKnockback: 1.2,
      lightPierce: 2,
      darkLifeSteal: 1.5,
    },
  },
  weapons: {
    referenceDamage: 25,
    referenceAttackInterval: 0.65,
    referenceRange: 10,
    basicAttack: {
      damage: 30, attackInterval: 0.6, range: 12, projectileSpeed: 17,
      projectileCount: 1, spread: 0, pierce: 0, knockback: 0.2,
    },
    pistol: {
      damage: 24, attackInterval: 0.62, range: 11, projectileSpeed: 18,
      projectileCount: 1, spread: 0.02, pierce: 1, knockback: 0.4,
    },
    smg: {
      damage: 8, attackInterval: 0.16, range: 8.5, projectileSpeed: 21,
      projectileCount: 1, spread: 0.1, pierce: 0, knockback: 0.15,
    },
    shotgun: {
      damage: 26, attackInterval: 0.9, range: 9, projectileSpeed: 16,
      projectileCount: 3, spread: 0.35, pierce: 0, knockback: 1.35,
    },
    upgrades: {
      damageMultiplier: 1.2,
      rangeMultiplier: 1.18,
      attackIntervalMultiplier: 0.84,
      pierceAdd: 1,
      projectileSpeedMultiplier: 1.2,
      accuracySpreadMultiplier: 0.65,
      pelletCountAdd: 1,
      shotgunSpreadMultiplier: 0.78,
      knockbackMultiplier: 1.25,
    },
  },
  shop: {
    itemCount: 3,
    maxPurchasesPerShop: 2,
    prices: { Common: 16, Uncommon: 21, Rare: 27 },
    recommendationMultiplier: 1.75,
    synergyUnlockRound: 6,
    /** Makes one matching weapon/evolution offer likely without forcing it into every shop. */
    synergyOfferWeightMultiplier: 10,
    baseRerollCost: 10,
  },
  spawning: {
    roundStartSpawnGraceSeconds: 3,
    interval: 1.4,
    /** Deliberately outside the current top-down combat view; enemies run in from the edge. */
    minDistance: 20,
    maxDistance: 22,
    maxAlive: 40,
  },
  progression: {
    firstLevelXp: 60,
    xpGrowth: 1.35,
  },
  camera: {
    fov: 48,
    near: 0.1,
    far: 120,
    offset: { x: 10, y: 14, z: 10 },
    followSharpness: 7,
  },
  loop: {
    maxDelta: 0.05,
  },
  debug: {
    armorGrant: 10,
    dodgeGrant: 0.15,
    hpRegenGrant: 2,
    pickupRangeGrant: 2,
  },
} as const
